# Generated by Django 4.0.5 on 2022-06-13 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default=None, max_length=255, null=True)),
                ('userPfp', models.ImageField(default=None, max_length=255, null=True, upload_to='')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagname', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('answers_num', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fk_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AskKozlovApp.profile')),
                ('fk_tags', models.ManyToManyField(to='AskKozlovApp.tag')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'questions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('marked_correct', models.BooleanField(default=False)),
                ('fk_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AskKozlovApp.profile')),
                ('fk_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AskKozlovApp.question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'db_table': 'answers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuestionRatingMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(1, 'up'), (-1, 'down'), (0, 'none')], default=0)),
                ('fk_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AskKozlovApp.profile')),
                ('fk_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AskKozlovApp.question')),
            ],
            options={
                'verbose_name': 'Q-VoteMark',
                'verbose_name_plural': 'Q-VoteMarks',
                'unique_together': {('fk_profile', 'fk_question')},
            },
        ),
        migrations.CreateModel(
            name='AnswerRatingMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(1, 'up'), (-1, 'down'), (0, 'none')], default=0)),
                ('fk_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AskKozlovApp.answer')),
                ('fk_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AskKozlovApp.profile')),
            ],
            options={
                'verbose_name': 'A-VoteMark',
                'verbose_name_plural': 'A-VoteMarks',
                'unique_together': {('fk_profile', 'fk_answer')},
            },
        ),
    ]
